baseURL = "https://tana2034-blog.netlify.com/"
languageCode = "ja"
title = "tana2034"
theme = "book"

[params]
  author = "tana2034"
  description = "mainly about programming language Ruby, Go and more."
